### ISSUE TITLE
Endless loading of Nether

### ISSUE THREAD

**Issue by BlackAures1** [Shadows-of-Fire/Wither-Skeleton-Tweaks#35]
WitherSkeletonTweaks-1.19.2-8.0.2
Modpack: [Gothic Edition](https://www.curseforge.com/minecraft/modpacks/play-as-dragon-gothic-edition)
Wither Skeleton has a conflict (presumably with the yung structure) which causes the game to cascade and the server to stop responding when trying to enter Nether. Crashing the game does not happen. Logs are not generated. I used visualvm to see the problem and there it is:

![image](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/assets/43911230/94bc666c-507b-4e3f-9e2c-5ab0cfe8e5eb)
![image](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/assets/43911230/442dcc83-c60b-49df-8163-a89662a0bba1)

Full: https://pastebin.com/zTVGhDpF 

Logs and debug are empty, but if you need them, here you go:
[debug.log](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/files/11742672/debug.log)
[latest.log](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/files/11742676/latest.log)

The important points: 
1. The world must be NEW (use my seed if it important - 121825627925). If you are using an old world with Nether already generated, you will not get this bug.
2. The player can contact the client (open inventory, move around the world, turn the camera), but the server part of the game completely dies.

**Comment by embeddedt** [comment]
At first glance this looks like a deadlock caused by adding an entity to the real world during worldgen.

**Comment by BlackAures1** [comment]
I'm not an expert on this

**Comment by Shadows-of-Fire** [comment]
Kinda surprised this hasn't been an issue before now. Weird. Trivial fix at least.

**Comment by son0fether** [comment]
I'm still getting what looks like the same hang with the 8.0.3 jar version that should have the fix, although it's with Integrated Dungeons and Structures.  It might be something different.  It's single-player, and I don't have a profiler.  Logs are empty, as above.  It's hard to get a minimal repro right now, although I've got one with several biome mods.

**Comment by Sniffity** [comment]
Hello!

I appear to be getting the same issue as reported above. Upon attempting to pregenerate the Nether dimension using Chunky I consisntently encounter a thread lock. I managed to get a stack trace for this which I am including as an attachment. 

Additionally, in my case I am able to consistently reproduce this issue in little time. I am not certain this will be the case with every mod list / seed combination, as I think it has something to do with worldgen and the event that is being fired. In case it is helpful, I have included a zip file with the mod list I am using. 
The level seed is: 
5404977835452663770
The command issued to Chunky that causes the issue is:
/chunky 

Of note: Setting  S:"All Biomes Chance" to 0 in the config file does stop the issue from ocurring.

Forgive the extensive reply, I do hope all the information provided helps you narrow this down!


[ModList 1.19.2.zip](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/files/11782597/ModList.1.19.2.zip)
[WST Stack Trace.txt](https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/files/11782598/WST.Stack.Trace.txt)

**Comment by Shadows-of-Fire** [comment]
Anyone experiencing this issue on 8.0.3 should repro a crash with this mod installed to retrieve the thread dump

https://www.curseforge.com/minecraft/mc-mods/fullstack-watchdog

**Comment by Dreytac** [comment]
I've been experiencing this crash as well on our server. I've uploaded the [latest.log with a ModernFix thread dump](https://gist.github.com/Dreytac/7b0ca257af9c9efa03062c1750f5b0e6). The offending lines are the same as with v8.0.2 (line 20571 of the latest.log). The way I fixed it was to remove the offending line entirely [witherSkel.moveTo()] and everything still seems to work correctly. Although, with my limited knowledge, I doubt that's a proper fix.

```
	at TRANSFORMER/wstweaks@8.0.3/shadows.wstweaks.WSTEvents.witherTransform(WSTEvents.java:41)
	at TRANSFORMER/wstweaks@8.0.3/shadows.wstweaks.__WSTEvents_witherTransform_SpecialSpawn.invoke(.dynamic)
```

**Comment by Gbergz** [comment]
Happening to me aswell, will dump crash report here: https://gist.githubusercontent.com/Gbergz/fa9d841b802f6d1c96a11a2e6d49136d/raw/34b4b147c080aa4b04a32432867b9a497e0170a6/gistfile1.txt

specific part
```
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Entity.m_7678_(Entity.java:1251)
	at TRANSFORMER/wstweaks@8.0.3/shadows.wstweaks.WSTEvents.witherTransform(WSTEvents.java:41)
	at TRANSFORMER/wstweaks@8.0.3/shadows.wstweaks.__WSTEvents_witherTransform_SpecialSpawn.invoke(.dynamic)
```

**Comment by Shadows-of-Fire** [comment]
Fixed in 8.0.4

**Comment by Xplodin** [comment]
Im having this issue on the latest WS tweaks and my modpack. I cannot figure out why.
However I enter the nether, SP/MP, it deadlocks and game locks up tps.
I try to save and quit and it freezes entirely in saving world and I have to task manager force close the game.
https://gist.github.com/Xplodin/3e8a66b963c8cce7bf983f88667a1d8d

**Comment by embeddedt** [comment]
This seems to be an issue with Pehkui.

**Comment by Xplodin** [comment]
> This seems to be an issue with Pehkui.

Is there a better way to debug this? Im still having the issue despite downgrading pehkui

**Comment by Shadows-of-Fire** [comment]
It may not be fixed via downgrade. You will likely need to report it to them and/or remove it in the meantime.

**Comment by embeddedt** [comment]
I don't think downgrading will fix it; you will likely have to remove that mod for now. I would suggest reporting this issue to them and providing the same log snippet.

EDIT: ninja'd, oops :eyes:

**Comment by ghost** [comment]
still an issue in latest 1.20.1 release. please fix
